### ISSUE TITLE
本地构建异常

### ISSUE THREAD

**Issue by mingmings** [PinkyJie/resume#1]
@PinkyJie hi，特别喜欢你的这个简历这个app的应用，想引用一下，但是master 分支拿下来之后进行本地grunt构建，发觉有一些异常，这个是否和我本地环境有关，我的环境是 `osx 10.10`, `node v0.11.0`, `npm v2.13.3`, `grunt v0.4.5` ，对前端不是很熟悉，学习了下 grunt，我不知道应该从哪里修改源码然后开始 building，可否允许我使用你的 resume 并且可否指导一下从哪里修改呢？

**Comment by PinkyJie** [comment]
需要安装ruby的，mac自带的，然后通过ruby的gem命令安装compass。我更新了readme，你再试试看。修改的话，主要是app目录下的cn.html和index.html，一个中文版一个英文版，如果对html不熟的话可以对照着页面看着改。

发自我的 iPhone

**Comment by mingmings** [comment]
@PinkyJie 多谢，基础环境这个之前做好的，只是不是前端岗，有点尴尬前端方面的知识欠缺。多谢解释，我再试试
